{% set name = "pydantic" %}
{% set version = "2.12.3" %}
{% set repo_url = "https://github.com/pydantic/pydantic" %}
{% set docs_url = "https://docs.pydantic.dev" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1da1c82b0fc140bb0103bc1441ffe062154c8d38491189751ee00fd8ca65ce74

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-fancy-pypi-readme >=22.5.0
    - pip
  run:
    - typing-inspection >=0.4.2
    - typing_extensions >=4.14.1
    - python >={{ python_min }}
    - typing-extensions >=4.6.1
    - annotated-types >=0.6.0
    - pydantic-core ==2.41.4

test:
  imports:
    - pydantic
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: {{ repo_url }}
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Data validation and settings management using python type hinting
  description: |
    Data validation and settings management using python type hinting.
    See documentation <{{ docs_url }}> for more details.
  doc_url: {{ docs_url }}
  dev_url: {{ repo_url }}

extra:
  recipe-maintainers:
    - thewchan
    - samuelcolvin
    - dgasmith
    - davidbrochart
    - pavelzw
