{% set name = "pydantic" %}
{% set version = "2.0" %}
{% set repo_url = "https://github.com/pydantic/pydantic" %}
{% set docs_url = "https://docs.pydantic.dev" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6e313661b310eb5b2c45168ce05d8dd79f57563adaf3906162a917585576b846

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - hatchling
    - hatch-fancy-pypi-readme
    - python
    - pip
    - cython
  run:
    - python
    - typing-extensions >=4.6.1
    - annotated-types >=0.4.0
    - pydantic-core ==2.0.1

test:
  imports:
    - {{ name }}

about:
  home: {{ repo_url }}
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Data validation and settings management using python type hinting
  description: |
    Data validation and settings management using python type hinting.
    See documentation <{{ docs_url }}> for more details.
  doc_url: {{ docs_url }}
  dev_url: {{ repo_url }}

extra:
  recipe-maintainers:
    - samuelcolvin
    - dgasmith
    - davidbrochart
    - pavelzw
