{% set name = "pydantic" %}
{% set version = "1.10.21" %}
{% set repo_url = "https://github.com/pydantic/pydantic" %}
{% set docs_url = "https://docs.pydantic.dev" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 64b48e2b609a6c22178a56c408ee1215a7206077ecb8a193e2fda31858b2362a

build:
  number: 0
  script: {{ PYTHON }} -m pip install -vv . --no-deps --ignore-installed --no-build-isolation --config-settings="--build-option=--cythonize"

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython >=3.0.0                         # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - setuptools >=68.0.0
    - pip
    - cython >=3.0.0
  run:
    - python
    - typing_extensions >=4.2.0

test:
  requires:
    - pip
    # Add a cython dependency for one particular version of python
    # to ensure that tests pass even with cython installed
    - cython      # [py==310]
    - cython  3   # [py==311]
  imports:
    - {{ name }}
  commands:
    - pip check

about:
  home: {{ repo_url }}
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Data validation and settings management using python type hinting
  description: |
    Data validation and settings management using python type hinting.
    See documentation <{{ docs_url }}> for more details.
  doc_url: {{ docs_url }}
  dev_url: {{ repo_url }}

extra:
  recipe-maintainers:
    - samuelcolvin
    - dgasmith
    - davidbrochart
    - pavelzw
