{% set name = "pydantic" %}
{% set version = "1.5.1" %}
{% set repo_url = "https://github.com/samuelcolvin/pydantic" %}
{% set docs_url = "https://pydantic-docs.helpmanual.io" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f0018613c7a0d19df3240c2a913849786f21b6539b9f23d85ce4067489dfacfa

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv
  skip: true  # [py2k or py35]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython  # [not win]
  run:
    - python
    - dataclasses >=0.6  # [py36]

test:
  imports:
    - {{ name }}

about:
  home: {{ repo_url }}
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Data validation and settings management using python type hinting
  description: |
    Data validation and settings management using python type hinting.
    See documentation <{{ docs_url }}> for more details.
  doc_url: {{ docs_url }}
  dev_url: {{ repo_url }}

extra:
  recipe-maintainers:
    - samuelcolvin
    - dgasmith
