{% set name = "pydantic" %}
{% set version = "1.10.22" %}
{% set repo_url = "https://github.com/pydantic/pydantic" %}
{% set docs_url = "https://docs.pydantic.dev" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ee1006cebd43a8e7158fb7190bb8f4e2da9649719bff65d0c287282ec38dec6d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=68.0.0
    - cython >=3.0.0
    - pip
  run:
    - typing_extensions >=4.2.0
    - python >={{ python_min }}

test:
  imports:
    - pydantic
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: {{ repo_url }}
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Data validation and settings management using python type hinting
  description: |
    Data validation and settings management using python type hinting.
    See documentation <{{ docs_url }}> for more details.
  doc_url: {{ docs_url }}
  dev_url: {{ repo_url }}

extra:
  recipe-maintainers:
    - thewchan
    - samuelcolvin
    - dgasmith
    - davidbrochart
    - pavelzw
