{% set name = "pydantic" %}
{% set version = "2.7.4" %}
{% set repo_url = "https://github.com/pydantic/pydantic" %}
{% set docs_url = "https://docs.pydantic.dev" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0c84efd9548d545f63ac0060c1e4d39bb9b14db8b3c0652338aecc07b5adec52

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - hatchling
    - hatch-fancy-pypi-readme >=22.5.0
    - pip
  run:
    - python >=3.7
    - typing-extensions >=4.6.1
    - annotated-types >=0.4.0
    - pydantic-core ==2.18.4

test:
  imports:
    - pydantic
  commands:
    - pip check
  requires:
    - pip

about:
  home: {{ repo_url }}
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Data validation and settings management using python type hinting
  description: |
    Data validation and settings management using python type hinting.
    See documentation <{{ docs_url }}> for more details.
  doc_url: {{ docs_url }}
  dev_url: {{ repo_url }}

extra:
  recipe-maintainers:
    - samuelcolvin
    - dgasmith
    - davidbrochart
    - pavelzw
