{% set name = "pydantic" %}
{% set version = "0.18.2" %}
{% set repo_url = "https://github.com/samuelcolvin/pydantic" %}
{% set docs_url = "https://pydantic-docs.helpmanual.io" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: edbb08b561feda505374c0f25e4b54466a0a0c702ed6b2efaabdc3890d1a82e7

build:
  number: 2
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - dataclasses >=0.6  # [py36]

test:
  imports:
    - {{ name }}

about:
  home: {{ repo_url }}
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Data validation and settings management using python type hinting'
  description: |
    Data validation and settings management using python type hinting.
    See documentation <{{ docs_url }}> for more details.
  doc_url: {{ docs_url }}
  dev_url: {{ repo_url }}

extra:
  recipe-maintainers:
  - samuelcolvin
  - dgasmith
