schema_version: 1

context:
  version: 2.14.0

package:
  name: pydantic
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/p/pydantic/pydantic-${{ version }}.tar.gz
  sha256: 8a51a7aaddd60f55566d1f07bdd87b92b463903f39a8f26b71a06314cd1548ae

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - hatch-fancy-pypi-readme >=22.5.0
    - pip
  run:
    - typing-inspection >=0.4.4
    - typing_extensions >=4.16.0
    - python >=${{ python_min }}
    - annotated-types >=0.6.0
    - pydantic-core ==2.50.0
tests:
  - python:
      imports:
        - pydantic
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - '*'

about:
  license: MIT
  license_file: LICENSE
  summary: Data validation and settings management using python type hinting
  description: |
    Data validation and settings management using python type hinting.
  homepage: https://github.com/pydantic/pydantic
  repository: https://github.com/pydantic/pydantic
  documentation: https://docs.pydantic.dev

extra:
  recipe-maintainers:
    - thewchan
    - samuelcolvin
    - dgasmith
    - davidbrochart
    - pavelzw
