github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
conda_build_tool: rattler-build
conda_forge_output_validation: true
conda_install_tool: pixi
bot:
  inspection: update-grayskull
  abi_migration_branches:
  - 1.x
